# Generated by Django 3.0.5 on 2020-07-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='store.MinCategory'),
        ),
    ]
