# Generated by Django 3.0.5 on 2020-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200704_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(to='store.MinCategory'),
        ),
    ]
