# Generated by Django 3.0.5 on 2020-07-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
