# Generated by Django 3.0.5 on 2020-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='mincategory',
            name='category',
            field=models.ManyToManyField(to='store.Category'),
        ),
    ]
