# Generated by Django 3.0.5 on 2020-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200706_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mincategory',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(to='store.MinCategory'),
        ),
    ]
