# Generated by Django 3.0.8 on 2020-07-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_mailbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='message',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='subject',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
